# Generated by Django 5.2.6 on 2025-10-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.TextField()),
                ('id_proof', models.ImageField(upload_to='customer_id_proofs/')),
            ],
        ),
    ]
