# Generated by Django 5.2.6 on 2025-10-19 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_customer_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.CharField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotelapp.room'),
        ),
    ]
