# Generated by Django 5.2.6 on 2025-10-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_room_log_room_id_alter_room_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('cust_id', models.IntegerField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
            ],
        ),
    ]
